import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const UIContext = createContext(null);

const DICTIONARY = {
  es: {
    feed_title: '¿Tenés ganas de jugar?',
    feed_subtitle: 'Encontrá partidos, torneos o un club y sumate.',
    filters: 'Filtros',
    courts: 'Canchas',
    global_cta: 'Me faltan jugadores',
    profile: 'Perfil',
    account: 'Cuenta',
    requests: 'Solicitudes',
    notifications: 'Notificaciones',
    search_placeholder: 'Buscar perfiles, clubes o canchas',
    search_empty: 'Empezá a escribir para buscar.',
    searching: 'Buscando...',
    no_results: 'No encontramos resultados con ese texto',
    view: 'Ver',
    message: 'Mensaje',
    contact: 'Contacto',
    added: 'Agregado',
    save_in_progress: 'Guardando...',
    menu: 'Menu',
    app_policies: 'Explicacion y politicas',
    send_suggestion: 'Enviar sugerencia',
    dark_mode: 'Tema oscuro',
    light_mode: 'Tema claro',
    language: 'Idioma',
    logout: 'Salir',
    suggestion_title: 'Enviar sugerencia',
    suggestion_placeholder: 'Contanos que mejorarias en la app...',
    send: 'Enviar',
    cancel: 'Cancelar',
    suggestion_sent: 'Sugerencia enviada',
    suggestion_error: 'No se pudo enviar la sugerencia',
    join: 'Quiero sumarme',
    menu_title: 'Opciones',
    search_min_chars: 'Escribi al menos 2 letras',
    search_unavailable: 'No se pudo buscar ahora',
    contact_added_status: 'Contacto agregado. Ya podes escribirle por mensaje directo.',
    contact_add_error: 'No se pudo agregar el contacto',
    view_all: 'Ver todas',
    loading: 'Cargando...',
    no_notifications: 'No hay notificaciones',
    notification_fallback: 'Notificacion',
    no_name: 'Sin nombre',
    no_location: 'Sin ubicacion',
    all: 'Todos',
    football_futsal: 'Futsal',
    football_5: 'F5',
    football_7: 'F7',
    football_9: 'F9',
    football_11: 'F11',
    req_match: 'Partido',
    req_tournament: 'Torneo',
    req_club: 'Club',
    gender_male: 'Masculino',
    gender_female: 'Femenino',
    gender_mixed: 'Mixto',
    filter_football_type: 'Tipo de futbol',
    filter_request_type: 'Tipo',
    filter_gender: 'Genero',
    apply_filters: 'Aplicar filtros',
    clear_filters: 'Limpiar filtros',
    close_filters: 'Cerrar filtros',
    filters_dialog: 'Filtros de publicaciones',
    courts_hint: 'Agrega cancha, horarios, disponibilidad y servicios.',
    filter_chip_football: 'Futbol',
    filter_chip_type: 'Tipo',
    filter_chip_gender: 'Genero',
    need_one_player: 'Falta 1 jugador',
    need_many_players: 'Faltan {count} jugadores',
    today: 'Hoy',
    tomorrow: 'Manana',
    could_not_load_matches: 'No se pudieron cargar los partidos.',
    app_policy_hint: 'Revisa las politicas de la app para este caso',
    abandon_policy_hint: 'Aplican politicas por abandono cercano al horario',
    request_sent: 'Solicitud enviada',
    join_error: 'Error al solicitar unirse',
    left_match: 'Saliste del partido',
    leave_error: 'Error al salir',
    request_cancelled: 'Solicitud cancelada',
    cancel_request_error: 'Error al cancelar solicitud',
    confirm_delete_match: 'Seguro queres eliminar este partido?',
    match_deleted: 'Partido eliminado',
    delete_match_error: 'Error al eliminar partido',
    application_sent: 'Postulacion enviada',
    application_error: 'Error al postularse',
    confirm_delete_club_request: 'Seguro queres eliminar esta busqueda de jugadores del club?',
    club_request_deleted: 'Peticion de club eliminada',
    delete_club_request_error: 'No se pudo eliminar la peticion',
    match_title: 'Partido F{type}',
    futsal_match_title: 'Partido Futsal',
    tournament_title: 'Torneo F{type}',
    club_recruitment_title: 'Busqueda de jugadores · {name}',
    club_recruitment_title_generic: 'Busqueda de jugadores · Club',
    empty_feed_title: 'No hay solicitudes compatibles para tu perfil',
    empty_feed_subtitle: 'Proba otro filtro o crea una solicitud nueva',
    search_players: 'Buscar jugadores',
    organize_by: 'Organiza',
    anonymous: 'Anonimo',
    slots: 'Cupos',
    goalkeepers_needed: '{count} arquero',
    goalkeepers_needed_plural: '{count} arqueros',
    open_recruitment: 'Busqueda abierta de jugadores',
    looking_for_position: 'Buscan {position}',
    contact_person: 'Contacto',
    km_from_you: '{km} km de vos',
    edit: 'Editar',
    delete: 'Eliminar',
    leave: 'Salir',
    cancel_request: 'Cancelar solicitud',
    full: 'Completo',
    view_club: 'Ver club',
    delete_request: 'Eliminar peticion',
  },
  en: {
    feed_title: 'Want to play?',
    feed_subtitle: 'Find matches, tournaments or a club and join in.',
    filters: 'Filters',
    courts: 'Courts',
    global_cta: 'Need more players',
    profile: 'Profile',
    account: 'Account',
    requests: 'Requests',
    notifications: 'Notifications',
    search_placeholder: 'Search profiles, clubs or venues',
    search_empty: 'Start typing to search.',
    searching: 'Searching...',
    no_results: 'No results found',
    view: 'View',
    message: 'Message',
    contact: 'Contact',
    added: 'Added',
    save_in_progress: 'Saving...',
    menu: 'Menu',
    app_policies: 'App info and policies',
    send_suggestion: 'Send suggestion',
    dark_mode: 'Dark theme',
    light_mode: 'Light theme',
    language: 'Language',
    logout: 'Log out',
    suggestion_title: 'Send suggestion',
    suggestion_placeholder: 'Tell us what you would improve in the app...',
    send: 'Send',
    cancel: 'Cancel',
    suggestion_sent: 'Suggestion sent',
    suggestion_error: 'Could not send suggestion',
    join: 'I want to join',
    menu_title: 'Options',
    search_min_chars: 'Type at least 2 characters',
    search_unavailable: 'Search is unavailable right now',
    contact_added_status: 'Contact added. You can now send a direct message.',
    contact_add_error: 'Could not add contact',
    view_all: 'View all',
    loading: 'Loading...',
    no_notifications: 'No notifications',
    notification_fallback: 'Notification',
    no_name: 'No name',
    no_location: 'No location',
    all: 'All',
    football_futsal: 'Futsal',
    football_5: 'F5',
    football_7: 'F7',
    football_9: 'F9',
    football_11: 'F11',
    req_match: 'Match',
    req_tournament: 'Tournament',
    req_club: 'Club',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_mixed: 'Mixed',
    filter_football_type: 'Football type',
    filter_request_type: 'Type',
    filter_gender: 'Gender',
    apply_filters: 'Apply filters',
    clear_filters: 'Clear filters',
    close_filters: 'Close filters',
    filters_dialog: 'Request filters',
    courts_hint: 'Add courts, schedules, availability and services.',
    filter_chip_football: 'Football',
    filter_chip_type: 'Type',
    filter_chip_gender: 'Gender',
    need_one_player: '1 player needed',
    need_many_players: '{count} players needed',
    today: 'Today',
    tomorrow: 'Tomorrow',
    could_not_load_matches: 'Could not load matches.',
    app_policy_hint: 'Check the app policies for this case',
    abandon_policy_hint: 'Abandonment policies apply close to kickoff time',
    request_sent: 'Request sent',
    join_error: 'Could not request to join',
    left_match: 'You left the match',
    leave_error: 'Error leaving the match',
    request_cancelled: 'Request cancelled',
    cancel_request_error: 'Error cancelling request',
    confirm_delete_match: 'Are you sure you want to delete this match?',
    match_deleted: 'Match deleted',
    delete_match_error: 'Error deleting match',
    application_sent: 'Application sent',
    application_error: 'Error applying',
    confirm_delete_club_request: 'Are you sure you want to delete this club player request?',
    club_request_deleted: 'Club request deleted',
    delete_club_request_error: 'Could not delete the request',
    match_title: 'Match F{type}',
    futsal_match_title: 'Futsal match',
    tournament_title: 'Tournament F{type}',
    club_recruitment_title: 'Player search · {name}',
    club_recruitment_title_generic: 'Player search · Club',
    empty_feed_title: 'No requests match your profile',
    empty_feed_subtitle: 'Try another filter or create a new request',
    search_players: 'Search players',
    organize_by: 'Hosted by',
    anonymous: 'Anonymous',
    slots: 'Slots',
    goalkeepers_needed: '{count} goalkeeper',
    goalkeepers_needed_plural: '{count} goalkeepers',
    open_recruitment: 'Open player search',
    looking_for_position: 'Looking for {position}',
    contact_person: 'Contact',
    km_from_you: '{km} km away',
    edit: 'Edit',
    delete: 'Delete',
    leave: 'Leave',
    cancel_request: 'Cancel request',
    full: 'Full',
    view_club: 'View club',
    delete_request: 'Delete request',
  },
  pt: {
    feed_title: 'Quer jogar?',
    feed_subtitle: 'Encontre partidas, torneios ou um clube e participe.',
    filters: 'Filtros',
    courts: 'Quadras',
    global_cta: 'Faltam jogadores',
    profile: 'Perfil',
    account: 'Conta',
    requests: 'Solicitacoes',
    notifications: 'Notificacoes',
    search_placeholder: 'Buscar perfis, clubes ou quadras',
    search_empty: 'Comece a digitar para buscar.',
    searching: 'Buscando...',
    no_results: 'Nao encontramos resultados',
    view: 'Ver',
    message: 'Mensagem',
    contact: 'Contato',
    added: 'Adicionado',
    save_in_progress: 'Salvando...',
    menu: 'Menu',
    app_policies: 'Explicacao e politicas',
    send_suggestion: 'Enviar sugestao',
    dark_mode: 'Tema escuro',
    light_mode: 'Tema claro',
    language: 'Idioma',
    logout: 'Sair',
    suggestion_title: 'Enviar sugestao',
    suggestion_placeholder: 'Conte o que melhoraria no app...',
    send: 'Enviar',
    cancel: 'Cancelar',
    suggestion_sent: 'Sugestao enviada',
    suggestion_error: 'Nao foi possivel enviar a sugestao',
    join: 'Quero participar',
    menu_title: 'Opcoes',
    search_min_chars: 'Digite pelo menos 2 caracteres',
    search_unavailable: 'Nao foi possivel buscar agora',
    contact_added_status: 'Contato adicionado. Agora voce pode enviar mensagem direta.',
    contact_add_error: 'Nao foi possivel adicionar contato',
    view_all: 'Ver todas',
    loading: 'Carregando...',
    no_notifications: 'Sem notificacoes',
    notification_fallback: 'Notificacao',
    no_name: 'Sem nome',
    no_location: 'Sem localizacao',
    all: 'Todos',
    football_futsal: 'Futsal',
    football_5: 'F5',
    football_7: 'F7',
    football_9: 'F9',
    football_11: 'F11',
    req_match: 'Partida',
    req_tournament: 'Torneio',
    req_club: 'Clube',
    gender_male: 'Masculino',
    gender_female: 'Feminino',
    gender_mixed: 'Misto',
    filter_football_type: 'Tipo de futebol',
    filter_request_type: 'Tipo',
    filter_gender: 'Genero',
    apply_filters: 'Aplicar filtros',
    clear_filters: 'Limpar filtros',
    close_filters: 'Fechar filtros',
    filters_dialog: 'Filtros de publicacoes',
    courts_hint: 'Adicione quadra, horarios, disponibilidade e servicos.',
    filter_chip_football: 'Futebol',
    filter_chip_type: 'Tipo',
    filter_chip_gender: 'Genero',
    need_one_player: 'Falta 1 jogador',
    need_many_players: 'Faltam {count} jogadores',
    today: 'Hoje',
    tomorrow: 'Amanha',
    could_not_load_matches: 'Nao foi possivel carregar as partidas.',
    app_policy_hint: 'Revise as politicas do app para este caso',
    abandon_policy_hint: 'Politicas de abandono se aplicam perto do horario',
    request_sent: 'Solicitacao enviada',
    join_error: 'Erro ao solicitar entrada',
    left_match: 'Voce saiu da partida',
    leave_error: 'Erro ao sair',
    request_cancelled: 'Solicitacao cancelada',
    cancel_request_error: 'Erro ao cancelar solicitacao',
    confirm_delete_match: 'Tem certeza que deseja excluir esta partida?',
    match_deleted: 'Partida excluida',
    delete_match_error: 'Erro ao excluir partida',
    application_sent: 'Inscricao enviada',
    application_error: 'Erro ao se inscrever',
    confirm_delete_club_request: 'Tem certeza que deseja excluir esta busca de jogadores do clube?',
    club_request_deleted: 'Pedido do clube excluido',
    delete_club_request_error: 'Nao foi possivel excluir o pedido',
    match_title: 'Partida F{type}',
    futsal_match_title: 'Partida de futsal',
    tournament_title: 'Torneio F{type}',
    club_recruitment_title: 'Busca de jogadores · {name}',
    club_recruitment_title_generic: 'Busca de jogadores · Clube',
    empty_feed_title: 'Nao ha solicitacoes compativeis com seu perfil',
    empty_feed_subtitle: 'Tente outro filtro ou crie uma nova solicitacao',
    search_players: 'Buscar jogadores',
    organize_by: 'Organiza',
    anonymous: 'Anonimo',
    slots: 'Vagas',
    goalkeepers_needed: '{count} goleiro',
    goalkeepers_needed_plural: '{count} goleiros',
    open_recruitment: 'Busca aberta de jogadores',
    looking_for_position: 'Buscam {position}',
    contact_person: 'Contato',
    km_from_you: '{km} km de voce',
    edit: 'Editar',
    delete: 'Excluir',
    leave: 'Sair',
    cancel_request: 'Cancelar solicitacao',
    full: 'Completo',
    view_club: 'Ver clube',
    delete_request: 'Excluir pedido',
  },
};

export function UIProvider({ children }) {
  const [theme, setTheme] = useState(() => {
    if (typeof window === 'undefined') return 'dark';
    const stored = window.localStorage.getItem('be_theme');
    return stored === 'light' ? 'light' : 'dark';
  });

  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'es';
    const stored = window.localStorage.getItem('be_language');
    return ['es', 'en', 'pt'].includes(stored) ? stored : 'es';
  });

  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.body.classList.toggle('light-theme', theme === 'light');
    window.localStorage.setItem('be_theme', theme);
  }, [theme]);

  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.documentElement.lang = language;
    window.localStorage.setItem('be_language', language);
  }, [language]);

  const value = useMemo(() => {
    const langDict = DICTIONARY[language] || DICTIONARY.es;
    const t = (key) => langDict[key] || DICTIONARY.es[key] || key;

    return {
      theme,
      setTheme,
      toggleTheme: () => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark')),
      language,
      setLanguage,
      t,
    };
  }, [theme, language]);

  return <UIContext.Provider value={value}>{children}</UIContext.Provider>;
}

export function useUI() {
  const ctx = useContext(UIContext);
  if (!ctx) throw new Error('useUI must be used within UIProvider');
  return ctx;
}
